Object position tests
LSSTDESC/imSim pull request #300
Opened 2022-10-31 22:49 UTC by jchiang87

2022-11-04 18:15 UTC, rmjarvis requested changes
Not sure if this is ready or not.  Has the underlying position issue been resolved?
Anyway, my comments are orthogonal to that.

2022-11-04 18:15 UTC, rmjarvis commented on imsim/photon_ops.py
> +        "camera": None
This should be `str` I think.  This is supposed to be whatever type is specified in the config file.  None isn't a type.  But in the imsim-config.yaml edit, you made it a string (copying the string in output.camera), so this should be specified as a string here.
Also, FYI, Geri updated how the telescope is specified in his branch (for the same reason -- an Optic cannot really be given in a yaml file).  That's now a str too.

2022-11-04 18:15 UTC, rmjarvis commented on tests/test_object_positions.py
> +        np.testing.assert_(offset < 2)
This test script isn't currently being run by CI.  If we want it to be, then it needs a `test_*` function (or other UnitTest class implementation).

2022-11-05 01:24 UTC, jchiang87 commented
@rmjarvis Thanks for the comments.  I think this ready for merging.

2022-11-05 21:54 UTC, rmjarvis approved these changes

2022-11-06 05:05 UTC, merged