Optical Path Difference outputs
LSSTDESC/imSim pull request #348
Opened 2023-06-02 22:38 UTC by jmeyers314

Adds ability to produce optical path difference (OPD) images as an extra output.  

Unit test compares directly with sample Zemax output.

2023-06-05 18:27 UTC, jmeyers314 commented
Added one more unrelated thing here: the ability to populate OpSimMeta directly from the config file.

2023-06-05 19:48 UTC, rmjarvis commented
> Added one more unrelated thing here: the ability to populate OpSimMeta directly from the config file.

I'm not a huge fan of this change, tbh.  I feel like this is solidifying some technical debt that I'd rather try to get away from if possible.  I think, rather than have a class implicitly get something from the OpSimMeta dict and then let the user specify that dict with custom values, we should instead let them override the OpSimMeta value in that class's part of the config dict directly.

E.g.
Rather than:
```
input:
    opsim_meta_dict:
        meta:
            observationStartMJD: 9293

image:
    type: LSST_CCD
    [...]
```
We should instead enable:
```
image:
    type: LSST_CCD
    [...]
    observationStartMJD: 9293
```
Or possibly something like
```
image:
    type: LSST_CCD
    [...]
    header_values:  # Values for the output header to use in lieu of getting them from an opsim_meta_dict
        observationStartMJD: 9293
```
The last is probably my preference.  But either of these are better than making the user populate a fake OpSimMeta dict.  That's kind of abusing the meaning of what that is supposed to be.

2023-06-06 20:50 UTC, rmjarvis requested changes

2023-06-06 22:47 UTC, jmeyers314 commented on imsim/opd.py
> +        ).fiducial
Hmm..  I was placing it here to "fail fast" if there's a config error.  E.g., if the telescope doesn't have a `sphereRadius` attribute and one isn't specified in the config either.  I could reload the telescope it in `finalize` I suppose.

2023-06-06 23:45 UTC, jmeyers314 commented on imsim/opd.py
> +        ).fiducial
Done.  Telescope is reloaded during finalize.

2023-06-07 01:37 UTC, rmjarvis commented on imsim/opd.py
> +            'telescope'
Oh, one other extremely minor thing I just noticed.  The last thing here should be 'opd', not 'telescope'.  It's only used for error messages, saying which thing needed the telescope input item if it fails to load.

2023-06-07 01:39 UTC, rmjarvis approved these changes

2023-06-07 17:01 UTC, merged